language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: i2IMu2vwKVC+5nJa/2yTdDNspoE4vlhXl02rLDqsAI7jkIaiWWfVXTmpjRSURzHxYpcavoCmI4L6svz6qFJWt8/kkUj9bpyTTqXmzIgWOG9qK66y5vjTODHI/PMaDxyvrB363v0bACTg0h/4tCQDFgar2y6ejg9cIxtWaYPVBKkSvVi93l7bliNYYjWgc3POz9VrDlsKVuH0NBnVrfaYNriCmo/TkSURtF4GIoHEOhgQE1RtSUE0TKuFghSzolwH92HYHa3w/YEh0IBtEtMYhHjgREv7g6o3rehM1dBUEeTHcqryi5l/O6lZlBBN45kQAZHbs9UcpuPrYGklmKJZ6KK4gMkt6unR2Vyx1KB3edQ/R3yrCo9a5UZ31Kx/L2VHe3tJJwD4qYFa49/cWopwgrs1hyqHATGb69O6qNrzGWH/j5jamt+hTfH+WtSipITKQvFPUXnSPtMFfWfkdCTcXkklQHFdnsvR1YQWMFnEtS2JJrQFEdQYLLWlHhV2HRiBpkG+g0wMSLABTnA8qfZsE47KpLcGFvdnN3/ck8UEtXzilyEpLvdnkKQ3TZOWYRo+5zVVuNZCtoYaDIklGdGlJrOa1moVNK4GvdoY06WTj8bY8cUcVWVMGAeTbvB8fEJ0iUB+kFcK8LND6KSCBHzOf68NdLPy7xs9IP5YMbp2kyQ=
  app: dart-local
cache:
  directories:
  - node_modules
