language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: F0Ij183Kw7eVCjlwoOajEx+eUwjwOfk1RNyVvNzbsU/bquF9RMgTHJ8qcV0jarllp4Ios33hAUOZRotXcnBxs8sUpuBDh+LGFp2LXxY2jAK+kTYi5NFY24rPnD20QOKyiIebO3NW25bn2bgwQA6vvgZzAGzLeW0VlCcu25mNFUgpcBs9RyWSiB7CDwFLDwNBkFhaM47XhTMArIdoqQgQAhc+QXAdEApWL2zXvAR8a17h6z/o7djrIvfGKTkc4PLL/akSC8rZN/ctsm5JX3GFy6y+4qkSnuVIR8EkPFlFPvbTtx9KI7Ir71uEgwkfJZ37lyEWmnyqSYs3qSBznh0FXD0E7hrfM+3NAHdB9MI6Kr3joqnaLxZ7oTsm+9t1dMWUQm8J/MPamaOF5sazL+dK0fkW5x9LrMbdQnfUHxGLBlq1vffwGk44YQNqkNVVC8Cm3Eo1J6DgkHPCtm5PbxOCN9hU29EbmfCu6FScfLidA5eDAsJgwJZplK9QnSkPbZTAhYGOPqjVIBUbvLel7W2datqOBK8u5MEledMGGudn7QtSeOQfvge4UZCicR9WBJXIyJ3BciClvVdERFGw79F2b9J12ys57wTVo1y9wUPNLXK23fq+lpBB2t3a3BRo5TL0jldcQnXLmmw/Bie3GyOf/0wtPbNYWVyfY2cSHDrAQto=
  app: dart-local
cache:
  directories:
  - node_modules
